name: Lint and Test

on: push

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm' # pnpmのキャッシュを設定
      - name: Install pnpm
        run: npm install -g pnpm # pnpmをグローバルにインストール
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Run Lint
        run: pnpm run lint
      - name: Run Test
        run: pnpm run test
